package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/jxsr12/oldegg/config"
	"github.com/jxsr12/oldegg/graph/model"
	"github.com/jxsr12/oldegg/service"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Login is the resolver for the login field.
func (r *authOpsResolver) Login(ctx context.Context, obj *model.AuthOps, email string, password string) (interface{}, error) {
	return service.UserLogin(ctx, email, password)
}

// Register is the resolver for the register field.
func (r *authOpsResolver) Register(ctx context.Context, obj *model.AuthOps, input model.NewUser) (interface{}, error) {
	return service.UserRegister(ctx, input)
}

// Auth is the resolver for the auth field.
func (r *mutationResolver) Auth(ctx context.Context) (*model.AuthOps, error) {
	return &model.AuthOps{}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.ChangeUser) (*model.User, error) {
	db := config.GetDB()

	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "Error, token gaada",
		}
	}

	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID

	user, _ := service.UserGetByID(ctx, userID)

	if user == nil {
		return nil, &gqlerror.Error{
			Message: "Error, user gaada",
		}
	}
	user.Name = input.Name
	user.Phone = input.Phone

	return user, db.Save(user).Error
}

// UpdateUserPassword is the resolver for the updateUserPassword field.
func (r *mutationResolver) UpdateUserPassword(ctx context.Context, oldpassword string, newpassword string) (*model.User, error) {
	db := config.GetDB()

	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "Error, token gaada",
		}
	}

	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID

	user, _ := service.UserGetByID(ctx, userID)

	if user == nil {
		return nil, &gqlerror.Error{
			Message: "Error, user gaada",
		}
	}

	if err := model.ComparePassword(user.Password, oldpassword); err != nil {
		return nil, &gqlerror.Error{
			Message: "Error, password lama salah",
		}
	}

	user.Password = model.HashPassword(newpassword)

	return user, db.Save(user).Error
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (interface{}, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// BanUser is the resolver for the banUser field.
func (r *mutationResolver) BanUser(ctx context.Context, id string) (*model.User, error) {
	// Check if user is authenticated and is an admin
	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "Error, token gaada",
		}
	}

	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID

	user, err := service.UserGetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	if user.Role != model.UserRoleAdmin {
		return nil, &gqlerror.Error{
			Message: "Error, not authorized to ban users",
		}
	}

	// Toggle the banned status of the user with the specified ID
	targetUser, err := service.UserGetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	targetUser.Banned = !targetUser.Banned

	// Manually save the updated user to the database
	err = config.GetDB().Model(&targetUser).Where("id = ?", id).Update("banned", targetUser.Banned).Error
	if err != nil {
		return nil, err
	}

	return targetUser, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return service.UserGetByID(ctx, id)
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context) (*model.User, error) {
	return service.UserGetByID(ctx, ctx.Value("auth").(*service.JwtCustomClaim).ID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return service.UserGetAll(ctx)
}

// Protected is the resolver for the protected field.
func (r *queryResolver) Protected(ctx context.Context) (string, error) {
	return "Success", nil
}

// CurrentSubscribedEmails is the resolver for the currentSubscribedEmails field.
func (r *queryResolver) CurrentSubscribedEmails(ctx context.Context) ([]string, error) {
	db := config.GetDB()

	// Check if user is authenticated and is admin
	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "No auth token",
		}
	}
	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID
	user, err := service.UserGetByID(ctx, userID)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Error getting user",
			Extensions: map[string]interface{}{
				"error": err.Error(),
			},
		}
	}
	if user.Role != model.UserRoleAdmin {
		return nil, &gqlerror.Error{
			Message: "Unauthorized to retrieve all emails",
		}
	}

	// Get all emails of users whose 'mailing' is set to true
	var emails []string
	err = db.Model(&model.User{}).Where("mailing = ?", true).Pluck("email", &emails).Error
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Error retrieving emails",
			Extensions: map[string]interface{}{
				"error": err.Error(),
			},
		}
	}

	return emails, nil
}

// NoShopUsers is the resolver for the noShopUsers field.
func (r *queryResolver) NoShopUsers(ctx context.Context) ([]*model.User, error) {
	db := config.GetDB()

	// Check if user is authenticated and is admin
	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "No auth token",
		}
	}
	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID
	user, err := service.UserGetByID(ctx, userID)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Error getting user",
			Extensions: map[string]interface{}{
				"error": err.Error(),
			},
		}
	}
	if user.Role != model.UserRoleAdmin {
		return nil, &gqlerror.Error{
			Message: "Unauthorized to retrieve no shop users",
		}
	}

	// Get all users that do not have a shop
	var users []*model.User
	err = db.Where("id NOT IN (SELECT user_id FROM shops)").Find(&users).Error
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Error retrieving no shop users",
			Extensions: map[string]interface{}{
				"error": err.Error(),
			},
		}
	}

	return users, nil
}

// OneTimeCode is the resolver for the oneTimeCode field.
func (r *userResolver) OneTimeCode(ctx context.Context, obj *model.User) (string, error) {
	panic(fmt.Errorf("not implemented: OneTimeCode - oneTimeCode"))
}

// AuthOps returns AuthOpsResolver implementation.
func (r *Resolver) AuthOps() AuthOpsResolver { return &authOpsResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type authOpsResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
